// Static/dynamic list of academic qualifications to be consumed by Qualifications component
// Logos should be placed in /public and referenced by absolute path

const QUALIFICATIONS = [
	{
		id: "edu-1",
		school: "Universidade Tiradentes",
		course: "Bacharelado em Ciência da Computação",
		start: "2021",
		end: "2025",
		location: "Aracaju, Brasil",
		logo: "/UnitLogo.webp",
		url: "https://unit.br",
		description: "Formação em fundamentos de computação, desenvolvimento de software e inteligência artificial, com foco em solução de problemas reais.",
		subjects: [
			"Estruturas de Dados",
			"Engenharia de Software",
			"Machine Learning",
			"Big Data Analysis",
			"Redes de Computadores"
		],
	},
	{
		id: "cert-1",
		school: "DIO.me",
		course: "Formação CI/CD",
		start: "2024",
		end: "2024",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Práticas de integração e entrega contínua aplicadas a pipelines modernos de desenvolvimento.",
		subjects: ["CI/CD", "Pipelines", "Automação de Deploy"],
	},
	{
		id: "cert-2",
		school: "DIO.me",
		course: "Formação .NET Developer",
		start: "2024",
		end: "2024",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Desenvolvimento de aplicações modernas com .NET, foco em APIs e boas práticas de arquitetura.",
		subjects: [".NET", "APIs REST", "Boas Práticas"],
	},
	{
		id: "cert-3",
		school: "DIO.me",
		course: "Azure para Devs",
		start: "2024",
		end: "2024",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Fundamentos de computação em nuvem e serviços Azure voltados para aplicações web.",
		subjects: ["Azure", "Cloud", "Serviços Gerenciados"],
	},
	{
		id: "cert-4",
		school: "DIO.me",
		course: "Formação DevOps",
		start: "2023",
		end: "2023",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Cultura DevOps, automação e monitoramento para ciclo de entrega mais rápido e confiável.",
		subjects: ["DevOps", "Observabilidade", "Automação"],
	},
	{
		id: "cert-5",
		school: "DIO.me",
		course: "Formação Python Developer",
		start: "2022",
		end: "2022",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Base sólida em Python para automação, análise de dados e desenvolvimento de aplicações.",
		subjects: ["Python", "Automação", "APIs"],
	},
	{
		id: "cert-6",
		school: "DIO.me",
		course: "Git e GitHub Developer",
		start: "2021",
		end: "2021",
		location: "Online",
		logo: "/DioLogo.png",
		url: "https://dio.me",
		description: "Fluxos de trabalho modernos com Git e GitHub para colaboração em projetos de software.",
		subjects: ["Git", "GitHub", "Workflow Colaborativo"],
	},
];

export default QUALIFICATIONS;

